<a href="https://colab.research.google.com/github/Samrajan2919/assignment/blob/master/Image_Perspective.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pyzbar

In [ ]:
import cv2
from pyzbar import pyzbar

In [ ]:
img=cv2.imread('/content/drive/My Drive/datamatrix_sample1_130x116.png')

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(img)

In [ ]:
 
from keras.preprocessing.image import ImageDataGenerator,array_to_img,img_to_array

In [ ]:
a=img_to_array(img)
a

In [ ]:
 import cv2
cv2.getPerspectiveTransform
import numpy as np

In [ ]:
width, height=250,350
point1=np.float32([[111,219],[287,188],[154,482],[357,445]])

In [ ]:
print(point1)

[[111. 219.]
 [287. 188.]
 [154. 482.]
 [357. 445.]]


In [ ]:
point2=np.float32([[0,0],[width,0],[0, height],[width, height]])
print (point2)

[[  0.   0.]
 [250.   0.]
 [  0. 350.]
 [250. 350.]]


In [ ]:
matrix=cv2.getPerspectiveTransform(point1,point2)
matrix

array([[ 1.59022163e+00, -2.59998214e-01, -1.19574993e+02],
       [ 3.04368503e-01,  1.72802763e+00, -4.12222955e+02],
       [ 9.14251206e-05,  6.67642549e-04,  1.00000000e+00]])

In [ ]:
output=cv2.warpPerspective(img,matrix,(width, height))
output

array([[[226, 226, 226],
        [227, 227, 227],
        [228, 228, 228],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       [[231, 231, 231],
        [231, 231, 231],
        [232, 232, 232],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       [[235, 235, 235],
        [235, 235, 235],
        [236, 236, 236],
        ...,
        [237, 237, 237],
        [237, 237, 237],
        [237, 237, 237]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 19,  19,  19],
        [ 18,  18,  18],
        [ 17,  17,  17]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 30,  30,  30],
        [ 27,  27,  27],
        [ 26,  26,  26]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 41,  41,  41],
        [ 39,  39,  39],
        [ 37,  37,  37]]

In [ ]:
for x in range (0,4):
  cv2.circle(img,(point1[x][0],point2[x][1]]),5,(0,0,255),cv2.FILLED)

In [ ]:
plt.imshow(img)

In [ ]:
plt.imshow(output)